// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.62.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.io.dart' if (dart.library.html) 'bridge_generated.web.dart';

abstract class XximSdk {
  Future<void> init({required String configStr, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kInitConstMeta;

  Future<void> setUserToken({required String token, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSetUserTokenConstMeta;
}

class XximSdkImpl implements XximSdk {
  final XximSdkPlatform _platform;
  factory XximSdkImpl(ExternalLibrary dylib) => XximSdkImpl.raw(XximSdkPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory XximSdkImpl.wasm(FutureOr<WasmModule> module) => XximSdkImpl(module as ExternalLibrary);
  XximSdkImpl.raw(this._platform);
  Future<void> init({required String configStr, dynamic hint}) {
    var arg0 = _platform.api2wire_String(configStr);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_init(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kInitConstMeta,
      argValues: [
        configStr
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kInitConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "init",
        argNames: [
          "configStr"
        ],
      );

  Future<void> setUserToken({required String token, dynamic hint}) {
    var arg0 = _platform.api2wire_String(token);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_set_user_token(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kSetUserTokenConstMeta,
      argValues: [
        token
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSetUserTokenConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "set_user_token",
        argNames: [
          "token"
        ],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  void _wire2api_unit(dynamic raw) {
    return;
  }
}

// Section: api2wire

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer
