// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.62.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.io.dart' if (dart.library.html) 'bridge_generated.web.dart';

abstract class XximSdk {
  Future<String> newInstance({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kNewInstanceConstMeta;

  Future<String> destroyInstance({required String param, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kDestroyInstanceConstMeta;

  Future<String> init({required String param, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kInitConstMeta;

  Future<String> setLoginInfo({required String param, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSetLoginInfoConstMeta;

  Future<String> unsetLoginInfo({required String param, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kUnsetLoginInfoConstMeta;
}

class XximSdkImpl implements XximSdk {
  final XximSdkPlatform _platform;
  factory XximSdkImpl(ExternalLibrary dylib) => XximSdkImpl.raw(XximSdkPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory XximSdkImpl.wasm(FutureOr<WasmModule> module) => XximSdkImpl(module as ExternalLibrary);
  XximSdkImpl.raw(this._platform);
  Future<String> newInstance({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_new_instance(port_),
      parseSuccessData: _wire2api_String,
      constMeta: kNewInstanceConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kNewInstanceConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "new_instance",
        argNames: [],
      );

  Future<String> destroyInstance({required String param, dynamic hint}) {
    var arg0 = _platform.api2wire_String(param);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_destroy_instance(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kDestroyInstanceConstMeta,
      argValues: [
        param
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kDestroyInstanceConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "destroy_instance",
        argNames: [
          "param"
        ],
      );

  Future<String> init({required String param, dynamic hint}) {
    var arg0 = _platform.api2wire_String(param);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_init(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kInitConstMeta,
      argValues: [
        param
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kInitConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "init",
        argNames: [
          "param"
        ],
      );

  Future<String> setLoginInfo({required String param, dynamic hint}) {
    var arg0 = _platform.api2wire_String(param);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_set_login_info(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kSetLoginInfoConstMeta,
      argValues: [
        param
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSetLoginInfoConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "set_login_info",
        argNames: [
          "param"
        ],
      );

  Future<String> unsetLoginInfo({required String param, dynamic hint}) {
    var arg0 = _platform.api2wire_String(param);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_unset_login_info(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kUnsetLoginInfoConstMeta,
      argValues: [
        param
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kUnsetLoginInfoConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "unset_login_info",
        argNames: [
          "param"
        ],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }
}

// Section: api2wire

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer
